apiVersion: apps/v1
kind: Deployment
metadata:
  name: decryption-client
  namespace: decryption-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: decryption-client
  template:
    metadata:
      labels:
        app: decryption-client
    spec:
      containers:
      - name: decryption-client
        image: decryption-client
        imagePullPolicy: Never
        env:
          - name: MASTER_HOST
            value: "decryption-master.decryption-service.svc.cluster.local"  
          - name: MASTER_PORT
            value: "4000"