apiVersion: apps/v1
kind: Deployment
metadata:
  name: decryption-master
  namespace: decryption-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: decryption-master
  template:
    metadata:
      labels:
        app: decryption-master
    spec:
      containers:
      - name: decryption-master
        image: decryption-master
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: input-volume
            mountPath: /app/inputs
          - name: output-volume
            mountPath: /app/outputs
      volumes:
        - name: input-volume
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Simon/source/repos/Nominal/NominalChallenge/Inputs
            type: Directory
        - name: output-volume
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Simon/source/repos/Nominal/NominalChallenge/Outputs
            type: DirectoryOrCreate