apiVersion: apps/v1
kind: Deployment
metadata:
  name: decryption-client
  namespace: decryption-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: decryption-client
  template:
    metadata:
      labels:
        app: decryption-client
    spec:
      containers:
      - name: decryption-client
        image: localhost:5000/decryption-client:latest
        env:
          - name: MASTER_HOST
            value: "master"  # Assuming DNS resolution is handled within the cluster
          - name: MASTER_PORT
            value: "4000"