apiVersion: v1
kind: Service
metadata:
  name: decryption-master
  namespace: decryption-service
spec:
  selector:
    app: decryption-master
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000